use_frameworks!

platform :ios, '9.0'

target 'RHQCocoapods_Example' do
  pod 'RHQCocoapods', :path => '../'

  target 'RHQCocoapods_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
